steps:
  - name: Test
    command: .buildkite/test.sh
  - name: Build
    command: .buildkite/build.sh
    artifact_paths: ci-playground
  - name: Deploy
    command: .buildkite/deploy.sh
    branches: 'master'
